
export const metadata = {
    title: 'Sign In | Clean Hub',
    description: 'Generated by create next app',
}
const BookingLayout = ({ children }) => {
    return children
};

export default BookingLayout;