import { Providers } from '../lib/Providers'
import './globals.css'
import Navbar from '../components/shared/Navbar'


export const metadata = {
  title: 'Clean Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body >
          <Navbar />
          {children}</body>
      </html>
    </Providers>
  )
}
