import { Providers } from '../lib/Providers'
import './globals.css'
import Navbar from '../components/shared/Navbar'
import Footer from '../components/shared/Footer'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Home | Clean Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body >
          <Navbar hasSider />
          {children}
          <ToastContainer theme="dark" />
          <Footer />
        </body>
      </html>
    </Providers>
  )
}
